### ISSUE TITLE
Not tested on Windows

### ISSUE THREAD

**Issue by phaebz** [sjbach/lusty-emacs#14]
Hi there!

I wanted to check out this package just now. First installed it via ELPA and then from git. Both show the same behavior. I am running emacs 24.0.92.1 on Windows.

When doing M-x lusty-file-explorer or lusty-buffer-explorer, the _Lusty-Matches_ buffer just shows --NO-MATCHES-- no matter what.

Any idea on debugging?

Best Regards,
Michael Bach

**Comment by p3r7** [comment]
I'm using it daily on both Windows (10 but used to be 7) and Linux and see no difference in behavior.

I assume this issue was only present on older versions of lusty.

**Comment by sjbach** [comment]
Good to hear. 👍
